server:
  port: 8888
  servlet:
    context-path: /config
spring:
  application:
    name: "@project.name@"
  main:
    banner-mode: 'OFF'
  cloud:
    config:
      server:
        git:
          default-label:
          searchPaths:
            - '*/**'
          uri: https://github.com/shoesclick/config--shoesclick-server.git
          username: claytonmorais@gmail.com
          password: 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
  security:
    basic:
      enabled: true
    user:
      name: develop
      password: develop

info:
   app:
     name: "@project.name@"
     version: "@project.version@"
     description: "@project.description@ "


management:
  server:
    port: 9091
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: diskSpace

opentracing:
  service-name: server--config-service
  jaeger:
    http-sender:
      url: ${JAEGER_HOST:http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces}