apiVersion: apps/v1
kind: Deployment
metadata:
  name: server--config-service-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: server--config-service
  template: 
    metadata:
        name: server--config-service
        labels:
          app: server--config-service
    spec:
        containers:
          - name: server--config-service-container
            image: $dck-accountid/$dck-repository:server--config-service-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev"
              - name: CONFIG_SERVER
                value: "http://svc-swapiconfigserver.shoes-eks.svc.cluster.local/config/"
            ports:
              - containerPort: 5000
              - containerPort: 9090
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
