apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server--config-service-hpa
  namespace: shoes-eks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server--config-service-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  