apiVersion: v1
kind: Service
metadata: 
  name: svc-server--config-service
  namespace: shoes-eks
spec:
  type: ClusterIP
  selector:
      app: server--config-service
  ports:
    - port: 8888
      name: http-8888
      protocol: TCP
      targetPort: 8888
    - port: 9090
      name: http-prometheus
      protocol: TCP
      targetPort: 9090